# Generated by Django 3.1.4 on 2021-02-06 06:56

from django.conf import settings
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=10, null=True)),
                ('alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('icon_image', models.ImageField(blank=True, default=home.models.get_default_icon_image, null=True, upload_to=home.models.get_icon_image_file_path)),
                ('major_image', models.ImageField(blank=True, default=home.models.get_default_major_iamge, null=True, upload_to=home.models.get_major_image_file_path)),
                ('secondary_image', models.ImageField(blank=True, default=home.models.get_default_secondary_iamge, null=True, upload_to=home.models.get_secondary_image_file_path)),
                ('tertiary_image', models.ImageField(blank=True, default=home.models.get_default_tertiary_iamge, null=True, upload_to=home.models.get_tertiary_image_file_path)),
                ('food_tag', models.ManyToManyField(to='home.Tag')),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
