# Generated by Django 3.1.6 on 2021-02-22 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210222_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kart',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='major_description',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='secondary_description',
            field=models.CharField(blank=True, default='NULL', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishes',
            name='tertiary_description',
            field=models.CharField(blank=True, default='NULL', max_length=40),
            preserve_default=False,
        ),
    ]
