# Generated by Django 3.1.4 on 2021-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='course',
            field=models.CharField(choices=[('Beverage', 'Beverage'), ('Starter', 'Starter'), ('Main-Course', 'Main-Course'), ('Dessert', 'Dessert')], max_length=65, null=True),
        ),
    ]
