# Generated by Django 3.1.6 on 2021-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210223_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dish_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
