# Generated by Django 3.1.6 on 2021-02-22 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210222_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
