# Generated by Django 3.1.4 on 2021-02-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='food_tag',
        ),
        migrations.AddField(
            model_name='dishes',
            name='food_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tag'),
        ),
    ]
