# Generated by Django 3.1.4 on 2021-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210207_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='like',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
