# Generated by Django 3.1.4 on 2021-02-11 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20210210_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('table_number', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delieverd', 'Delivered')], max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('ordered_dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dish', to='home.dishes')),
            ],
        ),
    ]
